# all versions are actual on 2025-11-05
# and compatible with Java 17
[versions]
activityCompose = "1.12.0"
coilCompose = "2.7.0"
core = "1.17.0"
composeBom = "2025.11.01"
googleTextFonts = "1.9.5"
googleJson = "2.13.2"
googlePlayLocation = "21.3.0"
koin = "4.1.1"
kotlinCoroutines = "1.10.2"
kotlinxDatetime = "0.7.1"
kotlinxSerialization = "2.2.21"
kotlinxSerializationJson = "1.9.0" #1.8.1
lifecycle = "2.10.0"
nav3Core = "1.0.0"
nav3Lifecycle = "2.10.0"

material3Adaptive = "1.2.0"
windowsizeclass = "1.4.0"

retrofit = "3.0.0"
retrofitLogging = "5.3.2"
room = "2.8.4"

# testing
androidTestCore = "1.7.0"
androidTestRunner = "1.7.0"
archCore = "2.2.0"
espresso = "3.7.0"
extJunit = "1.3.0"
junit = "4.13.2"
robolectric = "4.12.2"
truth = "1.7.0"
turbine = "1.2.1"
manifest = "1.9.5"
mockk = "1.14.6"

# plugins
agp = "8.13.1"
kotlin = "2.2.21"    #"2.0.21"
ksp = "2.2.21-2.0.4"


[libraries]
# Kotlin coroutines, datetime and serialization
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime"}
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

# Activy + Compose (libs with no version numbers, belongs to BOM)
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-animation = { module = "androidx.compose.animation:animation" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-material3-adaptive = { module = "androidx.compose.material3.adaptive:adaptive-navigation-android", version.ref = "material3Adaptive" }
androidx-material3-windowsizeclass = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "windowsizeclass" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-ui-text-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "googleTextFonts" }

# Android Lifecycle
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "nav3Lifecycle" }

# Android Navigation 3
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }

# Android Room database
androidx-room-ktx       = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime   = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler  = { module = "androidx.room:room-compiler", version.ref = "room" }

# Koin dependency injection
koin-core               = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android            = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose   = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

# Coil image processing
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }

# Retrofit webservices
gson-json = {  module = "com.google.code.gson:gson", version.ref = "googleJson" }
retrofit2-core = { module ="com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit2-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "retrofitLogging" }

# Google Play Services Location API
gplay-location = { module = "com.google.android.gms:play-services-location", version.ref = "googlePlayLocation" }

# testing ##########################################################################
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-core =            { module = "androidx.test:core", version.ref = "androidTestCore" }
androidx-test-core-ktx =        { module = "androidx.test:core-ktx", version.ref = "androidTestCore" }

androidx-test-espresso-core =   { module = "androidx.test.espresso:espresso-core",  version.ref = "espresso" }
androidx-test-ext-junit =       { module = "androidx.test.ext:junit",               version.ref = "extJunit" }
androidx-test-ext-junit-ktx =   { module = "androidx.test.ext:junit-ktx",           version.ref = "extJunit" }
androidx-test-ext-truth =       { module = "androidx.test.ext:truth",               version.ref = "truth" }
androidx-test-runner =          { module = "androidx.test:runner",                  version.ref = "androidTestRunner" }
androidx-ui-test-junit4 =       { module = "androidx.compose.ui:ui-test-junit4" }
androidx-room-testing =         { module = "androidx.room:room-testing", version.ref = "room" }
androidx-arch-core-testing =    { module = "androidx.arch.core:core-testing", version.ref = "archCore" }

koin-test =         { module = "io.insert-koin:koin-test",          version.ref = "koin" }
koin-test-junit4 =  { module = "io.insert-koin:koin-test-junit4",   version.ref = "koin" }
koin-android-test = { module = "io.insert-koin:koin-android-test",  version.ref = "koin" }

kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }

mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }

robolectric-test =  { module = "org.robolectric:robolectric",       version.ref = "robolectric" }
turbine-test =      { module = "app.cash.turbine:turbine",          version.ref = "turbine"}

# debugging ###########################################################################
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "manifest" }

[plugins]
android-application =   { id = "com.android.application",                   version.ref = "agp" }
kotlin-android =        { id = "org.jetbrains.kotlin.android",              version.ref = "kotlin" }
kotlin-compose =        { id = "org.jetbrains.kotlin.plugin.compose",       version.ref = "kotlin" }
kotlin-serialization =  { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinxSerialization" }
google-devtools-ksp =   { id = "com.google.devtools.ksp",                   version.ref = "ksp" }